name: main

env:
  PACKAGE_NAME: "mcp-server-drupal"
  TARGET_LIST: "bun-linux-x64-modern,bun-linux-arm64,bun-windows-x64-modern,bun-darwin-arm64,bun-darwin-x64"

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run biome ci --reporter=github

  build-and-release:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - run: bun install
      - run: |
          for target in $(echo $TARGET_LIST | tr "," "\n")
          do
            binary_name=$(echo $target | sed "s/^bun-/$PACKAGE_NAME-${{ steps.package-version.outputs.current-version}}-/" | sed "s/-/_/g")
            bun build --compile --target=$target --minify --sourcemap --bytecode ./src/index.ts --outfile ./build/$binary_name
          done
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*
